
# Use Python 3.12 as the base image
FROM python:3.12-slim

# Set working directory in the container
WORKDIR /app

# Install system dependencies required for OpenCV and other packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements file
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy main files
COPY main.py .
COPY DockerFile .

# Copy all project folders explicitly
COPY model/ ./model/
COPY object_detection/ ./object_detection/
COPY utils/ ./utils/


# Expose the port that FastAPI will run on
# To access this port from the host, use the -p flag when running the container
# Example: docker run -p 8000:8000 image_name
EXPOSE 8000

# Command to run the application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
